package com.ua.advertikon.helper;

import java.util.*;

public class Country {
	protected HashMap<String, String> name = new HashMap<>();

	public Country() {
		name.put( "AD","Andorra" );
		name.put( "AE","United Arab Emirates" );
		name.put( "AF","Afghanistan" );
		name.put( "AG","Antigua and Barbuda" );
		name.put( "AI","Anguilla" );
		name.put( "AL","Albania" );
		name.put( "AM","Armenia" );
		name.put( "AO","Angola" );
		name.put( "AP","Asia/Pacific Region" );
		name.put( "AQ","Antarctica" );
		name.put( "AR","Argentina" );
		name.put( "AS","American Samoa" );
		name.put( "AT","Austria" );
		name.put( "AU","Australia" );
		name.put( "AW","Aruba" );
		name.put( "AX","Aland Islands" );
		name.put( "AZ","Azerbaijan" );
		name.put( "BA","Bosnia and Herzegovina" );
		name.put( "BB","Barbados" );
		name.put( "BD","Bangladesh" );
		name.put( "BE","Belgium" );
		name.put( "BF","Burkina Faso" );
		name.put( "BG","Bulgaria" );
		name.put( "BH","Bahrain" );
		name.put( "BI","Burundi" );
		name.put( "BJ","Benin" );
		name.put( "BL","Saint Bartelemey" );
		name.put( "BM","Bermuda" );
		name.put( "BN","Brunei Darussalam" );
		name.put( "BO","Bolivia" );
		name.put( "BQ","Bonaire, Saint Eustatius and Saba" );
		name.put( "BR","Brazil" );
		name.put( "BS","Bahamas" );
		name.put( "BT","Bhutan" );
		name.put( "BV","Bouvet Island" );
		name.put( "BW","Botswana" );
		name.put( "BY","Belarus" );
		name.put( "BZ","Belize" );
		name.put( "CA","Canada" );
		name.put( "CC","Cocos (Keeling) Islands" );
		name.put( "CD","Congo, The Democratic Republic of the" );
		name.put( "CF","Central African Republic" );
		name.put( "CG","Congo" );
		name.put( "CH","Switzerland" );
		name.put( "CI","Cote d'Ivoire" );
		name.put( "CK","Cook Islands" );
		name.put( "CL","Chile" );
		name.put( "CM","Cameroon" );
		name.put( "CN","China" );
		name.put( "CO","Colombia" );
		name.put( "CR","Costa Rica" );
		name.put( "CU","Cuba" );
		name.put( "CV","Cape Verde" );
		name.put( "CW","Curacao" );
		name.put( "CX","Christmas Island" );
		name.put( "CY","Cyprus" );
		name.put( "CZ","Czech Republic" );
		name.put( "DE","Germany" );
		name.put( "DJ","Djibouti" );
		name.put( "DK","Denmark" );
		name.put( "DM","Dominica" );
		name.put( "DO","Dominican Republic" );
		name.put( "DZ","Algeria" );
		name.put( "EC","Ecuador" );
		name.put( "EE","Estonia" );
		name.put( "EG","Egypt" );
		name.put( "EH","Western Sahara" );
		name.put( "ER","Eritrea" );
		name.put( "ES","Spain" );
		name.put( "ET","Ethiopia" );
		name.put( "EU","Europe" );
		name.put( "FI","Finland" );
		name.put( "FJ","Fiji" );
		name.put( "FK","Falkland Islands (Malvinas)" );
		name.put( "FM","Micronesia, Federated States of" );
		name.put( "FO","Faroe Islands" );
		name.put( "FR","France" );
		name.put( "GA","Gabon" );
		name.put( "GB","United Kingdom" );
		name.put( "GD","Grenada" );
		name.put( "GE","Georgia" );
		name.put( "GF","French Guiana" );
		name.put( "GG","Guernsey" );
		name.put( "GH","Ghana" );
		name.put( "GI","Gibraltar" );
		name.put( "GL","Greenland" );
		name.put( "GM","Gambia" );
		name.put( "GN","Guinea" );
		name.put( "GP","Guadeloupe" );
		name.put( "GQ","Equatorial Guinea" );
		name.put( "GR","Greece" );
		name.put( "GS","South Georgia and the South Sandwich Islands" );
		name.put( "GT","Guatemala" );
		name.put( "GU","Guam" );
		name.put( "GW","Guinea-Bissau" );
		name.put( "GY","Guyana" );
		name.put( "HK","Hong Kong" );
		name.put( "HM","Heard Island and McDonald Islands" );
		name.put( "HN","Honduras" );
		name.put( "HR","Croatia" );
		name.put( "HT","Haiti" );
		name.put( "HU","Hungary" );
		name.put( "ID","Indonesia" );
		name.put( "IE","Ireland" );
		name.put( "IL","Israel" );
		name.put( "IM","Isle of Man" );
		name.put( "IN","India" );
		name.put( "IO","British Indian Ocean Territory" );
		name.put( "IQ","Iraq" );
		name.put( "IR","Iran, Islamic Republic of" );
		name.put( "IS","Iceland" );
		name.put( "IT","Italy" );
		name.put( "JE","Jersey" );
		name.put( "JM","Jamaica" );
		name.put( "JO","Jordan" );
		name.put( "JP","Japan" );
		name.put( "KE","Kenya" );
		name.put( "KG","Kyrgyzstan" );
		name.put( "KH","Cambodia" );
		name.put( "KI","Kiribati" );
		name.put( "KM","Comoros" );
		name.put( "KN","Saint Kitts and Nevis" );
		name.put( "KP","Korea, Democratic People's Republic of" );
		name.put( "KR","Korea, Republic of" );
		name.put( "KW","Kuwait" );
		name.put( "KY","Cayman Islands" );
		name.put( "KZ","Kazakhstan" );
		name.put( "LA","Lao People's Democratic Republic" );
		name.put( "LB","Lebanon" );
		name.put( "LC","Saint Lucia" );
		name.put( "LI","Liechtenstein" );
		name.put( "LK","Sri Lanka" );
		name.put( "LR","Liberia" );
		name.put( "LS","Lesotho" );
		name.put( "LT","Lithuania" );
		name.put( "LU","Luxembourg" );
		name.put( "LV","Latvia" );
		name.put( "LY","Libyan Arab Jamahiriya" );
		name.put( "MA","Morocco" );
		name.put( "MC","Monaco" );
		name.put( "MD","Moldova, Republic of" );
		name.put( "ME","Montenegro" );
		name.put( "MF","Saint Martin" );
		name.put( "MG","Madagascar" );
		name.put( "MH","Marshall Islands" );
		name.put( "MK","Macedonia" );
		name.put( "ML","Mali" );
		name.put( "MM","Myanmar" );
		name.put( "MN","Mongolia" );
		name.put( "MO","Macao" );
		name.put( "MP","Northern Mariana Islands" );
		name.put( "MQ","Martinique" );
		name.put( "MR","Mauritania" );
		name.put( "MS","Montserrat" );
		name.put( "MT","Malta" );
		name.put( "MU","Mauritius" );
		name.put( "MV","Maldives" );
		name.put( "MW","Malawi" );
		name.put( "MX","Mexico" );
		name.put( "MY","Malaysia" );
		name.put( "MZ","Mozambique" );
		name.put( "NA","Namibia" );
		name.put( "NC","New Caledonia" );
		name.put( "NE","Niger" );
		name.put( "NF","Norfolk Island" );
		name.put( "NG","Nigeria" );
		name.put( "NI","Nicaragua" );
		name.put( "NL","Netherlands" );
		name.put( "NO","Norway" );
		name.put( "NP","Nepal" );
		name.put( "NR","Nauru" );
		name.put( "NU","Niue" );
		name.put( "NZ","New Zealand" );
		name.put( "OM","Oman" );
		name.put( "PA","Panama" );
		name.put( "PE","Peru" );
		name.put( "PF","French Polynesia" );
		name.put( "PG","Papua New Guinea" );
		name.put( "PH","Philippines" );
		name.put( "PK","Pakistan" );
		name.put( "PL","Poland" );
		name.put( "PM","Saint Pierre and Miquelon" );
		name.put( "PN","Pitcairn" );
		name.put( "PR","Puerto Rico" );
		name.put( "PS","Palestinian Territory" );
		name.put( "PT","Portugal" );
		name.put( "PW","Palau" );
		name.put( "PY","Paraguay" );
		name.put( "QA","Qatar" );
		name.put( "RE","Reunion" );
		name.put( "RO","Romania" );
		name.put( "RS","Serbia" );
		name.put( "RU","Russian Federation" );
		name.put( "RW","Rwanda" );
		name.put( "SA","Saudi Arabia" );
		name.put( "SB","Solomon Islands" );
		name.put( "SC","Seychelles" );
		name.put( "SD","Sudan" );
		name.put( "SE","Sweden" );
		name.put( "SG","Singapore" );
		name.put( "SH","Saint Helena" );
		name.put( "SI","Slovenia" );
		name.put( "SJ","Svalbard and Jan Mayen" );
		name.put( "SK","Slovakia" );
		name.put( "SL","Sierra Leone" );
		name.put( "SM","San Marino" );
		name.put( "SN","Senegal" );
		name.put( "SO","Somalia" );
		name.put( "SR","Suriname" );
		name.put( "SS","South Sudan" );
		name.put( "ST","Sao Tome and Principe" );
		name.put( "SV","El Salvador" );
		name.put( "SX","Sint Maarten" );
		name.put( "SY","Syrian Arab Republic" );
		name.put( "SZ","Swaziland" );
		name.put( "TC","Turks and Caicos Islands" );
		name.put( "TD","Chad" );
		name.put( "TF","French Southern Territories" );
		name.put( "TG","Togo" );
		name.put( "TH","Thailand" );
		name.put( "TJ","Tajikistan" );
		name.put( "TK","Tokelau" );
		name.put( "TL","Timor-Leste" );
		name.put( "TM","Turkmenistan" );
		name.put( "TN","Tunisia" );
		name.put( "TO","Tonga" );
		name.put( "TR","Turkey" );
		name.put( "TT","Trinidad and Tobago" );
		name.put( "TV","Tuvalu" );
		name.put( "TW","Taiwan" );
		name.put( "TZ","Tanzania, United Republic of" );
		name.put( "UA","Ukraine" );
		name.put( "UG","Uganda" );
		name.put( "UM","United States Minor Outlying Islands" );
		name.put( "US","United States" );
		name.put( "UY","Uruguay" );
		name.put( "UZ","Uzbekistan" );
		name.put( "VA","Holy See (Vatican City State)" );
		name.put( "VC","Saint Vincent and the Grenadines" );
		name.put( "VE","Venezuela" );
		name.put( "VG","Virgin Islands, British" );
		name.put( "VI","Virgin Islands, U.S." );
		name.put( "VN","Vietnam" );
		name.put( "VU","Vanuatu" );
		name.put( "WF","Wallis and Futuna" );
		name.put( "WS","Samoa" );
		name.put( "YE","Yemen" );
		name.put( "YT","Mayotte" );
		name.put( "ZA","South Africa" );
		name.put( "ZM","Zambia" );
		name.put( "ZW","Zimbabwe" );
	}

	public String getNameByCode( String code ) {
		return name.getOrDefault( code.toUpperCase(), "" );
	}
}