/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOT = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int HLFLOAT = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int PRODUCT = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int POWER = 14;
  /** RegularExpression Id. */
  int SQRT = 15;
  /** RegularExpression Id. */
  int LOG10 = 16;
  /** RegularExpression Id. */
  int SIN = 17;
  /** RegularExpression Id. */
  int COS = 18;
  /** RegularExpression Id. */
  int TAN = 19;
  /** RegularExpression Id. */
  int ASIN = 20;
  /** RegularExpression Id. */
  int ACOS = 21;
  /** RegularExpression Id. */
  int ATAN = 22;
  /** RegularExpression Id. */
  int LOG = 23;
  /** RegularExpression Id. */
  int EOL = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\".\"",
    "<DIGIT>",
    "<FLOAT>",
    "<HLFLOAT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"^\"",
    "\"sqrt\"",
    "\"log10\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"asin\"",
    "\"acos\"",
    "\"atan\"",
    "\"log\"",
    "\"\\n\"",
  };

}
